/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as EmergencyTokenRouteImport } from './routes/emergency/$token'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicHelpRouteImport } from './routes/_public/help'
import { Route as PublicGeoAssistanceRouteImport } from './routes/_public/geo-assistance'
import { Route as PublicCampsRouteImport } from './routes/_public/camps'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as ApiChatIndexRouteImport } from './routes/api/chat/index'
import { Route as DashboardDashboardIndexRouteImport } from './routes/_dashboard/dashboard/index'
import { Route as ApiCronNotifyRemindersRouteImport } from './routes/api/cron/notify-reminders'
import { Route as ApiCronNotifyAppointmentsRouteImport } from './routes/api/cron/notify-appointments'
import { Route as ApiChatTtsRouteImport } from './routes/api/chat/tts'
import { Route as ApiChatTranscribeRouteImport } from './routes/api/chat/transcribe'
import { Route as ApiChatRetitleRouteImport } from './routes/api/chat/retitle'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as DashboardDashboardSettingsRouteImport } from './routes/_dashboard/dashboard/settings'
import { Route as DashboardDashboardRemindersRouteImport } from './routes/_dashboard/dashboard/reminders'
import { Route as DashboardDashboardQrCodeRouteImport } from './routes/_dashboard/dashboard/qr-code'
import { Route as DashboardDashboardProfileRouteImport } from './routes/_dashboard/dashboard/profile'
import { Route as DashboardDashboardHealthRouteImport } from './routes/_dashboard/dashboard/health'
import { Route as DashboardDashboardDocumentsRouteImport } from './routes/_dashboard/dashboard/documents'
import { Route as DashboardDashboardDeveloperRouteImport } from './routes/_dashboard/dashboard/developer'
import { Route as DashboardDashboardChatRouteImport } from './routes/_dashboard/dashboard/chat'
import { Route as DashboardDashboardAppointmentsRouteImport } from './routes/_dashboard/dashboard/appointments'
import { Route as DashboardDashboardChatChatIdRouteImport } from './routes/_dashboard/dashboard/chat.$chatId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const EmergencyTokenRoute = EmergencyTokenRouteImport.update({
  id: '/emergency/$token',
  path: '/emergency/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHelpRoute = PublicHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => PublicRoute,
} as any)
const PublicGeoAssistanceRoute = PublicGeoAssistanceRouteImport.update({
  id: '/geo-assistance',
  path: '/geo-assistance',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCampsRoute = PublicCampsRouteImport.update({
  id: '/camps',
  path: '/camps',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const ApiChatIndexRoute = ApiChatIndexRouteImport.update({
  id: '/api/chat/',
  path: '/api/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardIndexRoute = DashboardDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiCronNotifyRemindersRoute = ApiCronNotifyRemindersRouteImport.update({
  id: '/api/cron/notify-reminders',
  path: '/api/cron/notify-reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronNotifyAppointmentsRoute =
  ApiCronNotifyAppointmentsRouteImport.update({
    id: '/api/cron/notify-appointments',
    path: '/api/cron/notify-appointments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatTtsRoute = ApiChatTtsRouteImport.update({
  id: '/api/chat/tts',
  path: '/api/chat/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatTranscribeRoute = ApiChatTranscribeRouteImport.update({
  id: '/api/chat/transcribe',
  path: '/api/chat/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRetitleRoute = ApiChatRetitleRouteImport.update({
  id: '/api/chat/retitle',
  path: '/api/chat/retitle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDashboardSettingsRoute =
  DashboardDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardRemindersRoute =
  DashboardDashboardRemindersRouteImport.update({
    id: '/dashboard/reminders',
    path: '/dashboard/reminders',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardQrCodeRoute =
  DashboardDashboardQrCodeRouteImport.update({
    id: '/dashboard/qr-code',
    path: '/dashboard/qr-code',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardProfileRoute =
  DashboardDashboardProfileRouteImport.update({
    id: '/dashboard/profile',
    path: '/dashboard/profile',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardHealthRoute =
  DashboardDashboardHealthRouteImport.update({
    id: '/dashboard/health',
    path: '/dashboard/health',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardDocumentsRoute =
  DashboardDashboardDocumentsRouteImport.update({
    id: '/dashboard/documents',
    path: '/dashboard/documents',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardDeveloperRoute =
  DashboardDashboardDeveloperRouteImport.update({
    id: '/dashboard/developer',
    path: '/dashboard/developer',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardChatRoute = DashboardDashboardChatRouteImport.update({
  id: '/dashboard/chat',
  path: '/dashboard/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDashboardAppointmentsRoute =
  DashboardDashboardAppointmentsRouteImport.update({
    id: '/dashboard/appointments',
    path: '/dashboard/appointments',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardDashboardChatChatIdRoute =
  DashboardDashboardChatChatIdRouteImport.update({
    id: '/$chatId',
    path: '/$chatId',
    getParentRoute: () => DashboardDashboardChatRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/about': typeof PublicAboutRoute
  '/camps': typeof PublicCampsRoute
  '/geo-assistance': typeof PublicGeoAssistanceRoute
  '/help': typeof PublicHelpRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/emergency/$token': typeof EmergencyTokenRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/appointments': typeof DashboardDashboardAppointmentsRoute
  '/dashboard/chat': typeof DashboardDashboardChatRouteWithChildren
  '/dashboard/developer': typeof DashboardDashboardDeveloperRoute
  '/dashboard/documents': typeof DashboardDashboardDocumentsRoute
  '/dashboard/health': typeof DashboardDashboardHealthRoute
  '/dashboard/profile': typeof DashboardDashboardProfileRoute
  '/dashboard/qr-code': typeof DashboardDashboardQrCodeRoute
  '/dashboard/reminders': typeof DashboardDashboardRemindersRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/retitle': typeof ApiChatRetitleRoute
  '/api/chat/transcribe': typeof ApiChatTranscribeRoute
  '/api/chat/tts': typeof ApiChatTtsRoute
  '/api/cron/notify-appointments': typeof ApiCronNotifyAppointmentsRoute
  '/api/cron/notify-reminders': typeof ApiCronNotifyRemindersRoute
  '/dashboard/': typeof DashboardDashboardIndexRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/dashboard/chat/$chatId': typeof DashboardDashboardChatChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/about': typeof PublicAboutRoute
  '/camps': typeof PublicCampsRoute
  '/geo-assistance': typeof PublicGeoAssistanceRoute
  '/help': typeof PublicHelpRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/emergency/$token': typeof EmergencyTokenRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard/appointments': typeof DashboardDashboardAppointmentsRoute
  '/dashboard/chat': typeof DashboardDashboardChatRouteWithChildren
  '/dashboard/developer': typeof DashboardDashboardDeveloperRoute
  '/dashboard/documents': typeof DashboardDashboardDocumentsRoute
  '/dashboard/health': typeof DashboardDashboardHealthRoute
  '/dashboard/profile': typeof DashboardDashboardProfileRoute
  '/dashboard/qr-code': typeof DashboardDashboardQrCodeRoute
  '/dashboard/reminders': typeof DashboardDashboardRemindersRoute
  '/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/retitle': typeof ApiChatRetitleRoute
  '/api/chat/transcribe': typeof ApiChatTranscribeRoute
  '/api/chat/tts': typeof ApiChatTtsRoute
  '/api/cron/notify-appointments': typeof ApiCronNotifyAppointmentsRoute
  '/api/cron/notify-reminders': typeof ApiCronNotifyRemindersRoute
  '/dashboard': typeof DashboardDashboardIndexRoute
  '/api/chat': typeof ApiChatIndexRoute
  '/dashboard/chat/$chatId': typeof DashboardDashboardChatChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_public/about': typeof PublicAboutRoute
  '/_public/camps': typeof PublicCampsRoute
  '/_public/geo-assistance': typeof PublicGeoAssistanceRoute
  '/_public/help': typeof PublicHelpRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/terms': typeof PublicTermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/emergency/$token': typeof EmergencyTokenRoute
  '/_public/': typeof PublicIndexRoute
  '/auth/': typeof AuthIndexRoute
  '/_dashboard/dashboard/appointments': typeof DashboardDashboardAppointmentsRoute
  '/_dashboard/dashboard/chat': typeof DashboardDashboardChatRouteWithChildren
  '/_dashboard/dashboard/developer': typeof DashboardDashboardDeveloperRoute
  '/_dashboard/dashboard/documents': typeof DashboardDashboardDocumentsRoute
  '/_dashboard/dashboard/health': typeof DashboardDashboardHealthRoute
  '/_dashboard/dashboard/profile': typeof DashboardDashboardProfileRoute
  '/_dashboard/dashboard/qr-code': typeof DashboardDashboardQrCodeRoute
  '/_dashboard/dashboard/reminders': typeof DashboardDashboardRemindersRoute
  '/_dashboard/dashboard/settings': typeof DashboardDashboardSettingsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/retitle': typeof ApiChatRetitleRoute
  '/api/chat/transcribe': typeof ApiChatTranscribeRoute
  '/api/chat/tts': typeof ApiChatTtsRoute
  '/api/cron/notify-appointments': typeof ApiCronNotifyAppointmentsRoute
  '/api/cron/notify-reminders': typeof ApiCronNotifyRemindersRoute
  '/_dashboard/dashboard/': typeof DashboardDashboardIndexRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/_dashboard/dashboard/chat/$chatId': typeof DashboardDashboardChatChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/about'
    | '/camps'
    | '/geo-assistance'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/emergency/$token'
    | '/auth/'
    | '/dashboard/appointments'
    | '/dashboard/chat'
    | '/dashboard/developer'
    | '/dashboard/documents'
    | '/dashboard/health'
    | '/dashboard/profile'
    | '/dashboard/qr-code'
    | '/dashboard/reminders'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/api/chat/retitle'
    | '/api/chat/transcribe'
    | '/api/chat/tts'
    | '/api/cron/notify-appointments'
    | '/api/cron/notify-reminders'
    | '/dashboard/'
    | '/api/chat/'
    | '/dashboard/chat/$chatId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/about'
    | '/camps'
    | '/geo-assistance'
    | '/help'
    | '/privacy'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/emergency/$token'
    | '/auth'
    | '/dashboard/appointments'
    | '/dashboard/chat'
    | '/dashboard/developer'
    | '/dashboard/documents'
    | '/dashboard/health'
    | '/dashboard/profile'
    | '/dashboard/qr-code'
    | '/dashboard/reminders'
    | '/dashboard/settings'
    | '/api/auth/$'
    | '/api/chat/retitle'
    | '/api/chat/transcribe'
    | '/api/chat/tts'
    | '/api/cron/notify-appointments'
    | '/api/cron/notify-reminders'
    | '/dashboard'
    | '/api/chat'
    | '/dashboard/chat/$chatId'
  id:
    | '__root__'
    | '/_dashboard'
    | '/_public'
    | '/auth'
    | '/onboarding'
    | '/_public/about'
    | '/_public/camps'
    | '/_public/geo-assistance'
    | '/_public/help'
    | '/_public/privacy'
    | '/_public/terms'
    | '/auth/forgot-password'
    | '/auth/login'
    | '/auth/reset-password'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/emergency/$token'
    | '/_public/'
    | '/auth/'
    | '/_dashboard/dashboard/appointments'
    | '/_dashboard/dashboard/chat'
    | '/_dashboard/dashboard/developer'
    | '/_dashboard/dashboard/documents'
    | '/_dashboard/dashboard/health'
    | '/_dashboard/dashboard/profile'
    | '/_dashboard/dashboard/qr-code'
    | '/_dashboard/dashboard/reminders'
    | '/_dashboard/dashboard/settings'
    | '/api/auth/$'
    | '/api/chat/retitle'
    | '/api/chat/transcribe'
    | '/api/chat/tts'
    | '/api/cron/notify-appointments'
    | '/api/cron/notify-reminders'
    | '/_dashboard/dashboard/'
    | '/api/chat/'
    | '/_dashboard/dashboard/chat/$chatId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  EmergencyTokenRoute: typeof EmergencyTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatRetitleRoute: typeof ApiChatRetitleRoute
  ApiChatTranscribeRoute: typeof ApiChatTranscribeRoute
  ApiChatTtsRoute: typeof ApiChatTtsRoute
  ApiCronNotifyAppointmentsRoute: typeof ApiCronNotifyAppointmentsRoute
  ApiCronNotifyRemindersRoute: typeof ApiCronNotifyRemindersRoute
  ApiChatIndexRoute: typeof ApiChatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/emergency/$token': {
      id: '/emergency/$token'
      path: '/emergency/$token'
      fullPath: '/emergency/$token'
      preLoaderRoute: typeof EmergencyTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/help': {
      id: '/_public/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof PublicHelpRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/geo-assistance': {
      id: '/_public/geo-assistance'
      path: '/geo-assistance'
      fullPath: '/geo-assistance'
      preLoaderRoute: typeof PublicGeoAssistanceRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/camps': {
      id: '/_public/camps'
      path: '/camps'
      fullPath: '/camps'
      preLoaderRoute: typeof PublicCampsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/api/chat/': {
      id: '/api/chat/'
      path: '/api/chat'
      fullPath: '/api/chat/'
      preLoaderRoute: typeof ApiChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardDashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/cron/notify-reminders': {
      id: '/api/cron/notify-reminders'
      path: '/api/cron/notify-reminders'
      fullPath: '/api/cron/notify-reminders'
      preLoaderRoute: typeof ApiCronNotifyRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/notify-appointments': {
      id: '/api/cron/notify-appointments'
      path: '/api/cron/notify-appointments'
      fullPath: '/api/cron/notify-appointments'
      preLoaderRoute: typeof ApiCronNotifyAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/tts': {
      id: '/api/chat/tts'
      path: '/api/chat/tts'
      fullPath: '/api/chat/tts'
      preLoaderRoute: typeof ApiChatTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/transcribe': {
      id: '/api/chat/transcribe'
      path: '/api/chat/transcribe'
      fullPath: '/api/chat/transcribe'
      preLoaderRoute: typeof ApiChatTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat/retitle': {
      id: '/api/chat/retitle'
      path: '/api/chat/retitle'
      fullPath: '/api/chat/retitle'
      preLoaderRoute: typeof ApiChatRetitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/dashboard/settings': {
      id: '/_dashboard/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardDashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/reminders': {
      id: '/_dashboard/dashboard/reminders'
      path: '/dashboard/reminders'
      fullPath: '/dashboard/reminders'
      preLoaderRoute: typeof DashboardDashboardRemindersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/qr-code': {
      id: '/_dashboard/dashboard/qr-code'
      path: '/dashboard/qr-code'
      fullPath: '/dashboard/qr-code'
      preLoaderRoute: typeof DashboardDashboardQrCodeRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/profile': {
      id: '/_dashboard/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardDashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/health': {
      id: '/_dashboard/dashboard/health'
      path: '/dashboard/health'
      fullPath: '/dashboard/health'
      preLoaderRoute: typeof DashboardDashboardHealthRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/documents': {
      id: '/_dashboard/dashboard/documents'
      path: '/dashboard/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/developer': {
      id: '/_dashboard/dashboard/developer'
      path: '/dashboard/developer'
      fullPath: '/dashboard/developer'
      preLoaderRoute: typeof DashboardDashboardDeveloperRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/chat': {
      id: '/_dashboard/dashboard/chat'
      path: '/dashboard/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardDashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/appointments': {
      id: '/_dashboard/dashboard/appointments'
      path: '/dashboard/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardDashboardAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/dashboard/chat/$chatId': {
      id: '/_dashboard/dashboard/chat/$chatId'
      path: '/$chatId'
      fullPath: '/dashboard/chat/$chatId'
      preLoaderRoute: typeof DashboardDashboardChatChatIdRouteImport
      parentRoute: typeof DashboardDashboardChatRoute
    }
  }
}

interface DashboardDashboardChatRouteChildren {
  DashboardDashboardChatChatIdRoute: typeof DashboardDashboardChatChatIdRoute
}

const DashboardDashboardChatRouteChildren: DashboardDashboardChatRouteChildren =
  {
    DashboardDashboardChatChatIdRoute: DashboardDashboardChatChatIdRoute,
  }

const DashboardDashboardChatRouteWithChildren =
  DashboardDashboardChatRoute._addFileChildren(
    DashboardDashboardChatRouteChildren,
  )

interface DashboardRouteChildren {
  DashboardDashboardAppointmentsRoute: typeof DashboardDashboardAppointmentsRoute
  DashboardDashboardChatRoute: typeof DashboardDashboardChatRouteWithChildren
  DashboardDashboardDeveloperRoute: typeof DashboardDashboardDeveloperRoute
  DashboardDashboardDocumentsRoute: typeof DashboardDashboardDocumentsRoute
  DashboardDashboardHealthRoute: typeof DashboardDashboardHealthRoute
  DashboardDashboardProfileRoute: typeof DashboardDashboardProfileRoute
  DashboardDashboardQrCodeRoute: typeof DashboardDashboardQrCodeRoute
  DashboardDashboardRemindersRoute: typeof DashboardDashboardRemindersRoute
  DashboardDashboardSettingsRoute: typeof DashboardDashboardSettingsRoute
  DashboardDashboardIndexRoute: typeof DashboardDashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDashboardAppointmentsRoute: DashboardDashboardAppointmentsRoute,
  DashboardDashboardChatRoute: DashboardDashboardChatRouteWithChildren,
  DashboardDashboardDeveloperRoute: DashboardDashboardDeveloperRoute,
  DashboardDashboardDocumentsRoute: DashboardDashboardDocumentsRoute,
  DashboardDashboardHealthRoute: DashboardDashboardHealthRoute,
  DashboardDashboardProfileRoute: DashboardDashboardProfileRoute,
  DashboardDashboardQrCodeRoute: DashboardDashboardQrCodeRoute,
  DashboardDashboardRemindersRoute: DashboardDashboardRemindersRoute,
  DashboardDashboardSettingsRoute: DashboardDashboardSettingsRoute,
  DashboardDashboardIndexRoute: DashboardDashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicCampsRoute: typeof PublicCampsRoute
  PublicGeoAssistanceRoute: typeof PublicGeoAssistanceRoute
  PublicHelpRoute: typeof PublicHelpRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicCampsRoute: PublicCampsRoute,
  PublicGeoAssistanceRoute: PublicGeoAssistanceRoute,
  PublicHelpRoute: PublicHelpRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  EmergencyTokenRoute: EmergencyTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatRetitleRoute: ApiChatRetitleRoute,
  ApiChatTranscribeRoute: ApiChatTranscribeRoute,
  ApiChatTtsRoute: ApiChatTtsRoute,
  ApiCronNotifyAppointmentsRoute: ApiCronNotifyAppointmentsRoute,
  ApiCronNotifyRemindersRoute: ApiCronNotifyRemindersRoute,
  ApiChatIndexRoute: ApiChatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
